apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay-deployment
  labels:
    type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: cowsay-cont
          image: docker.io/awsclouddev/cowsay-wisdom:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4499

---
apiVersion: v1
kind: Service
metadata:
  name: cowsay-deployment-svc
  labels:
    type: app
spec:
  type: NodePort
  selector:
    type: app
  ports:
    - port: 4499
      targetPort: 4499
      nodePort: 30003
